### ISSUE TITLE
Why not modify the .htaccess and restore it?

### ISSUE THREAD

**Issue by gremo** [matatirosolutions/CorleyMaintenanceBundle#11]
Hello, clever bundle. A suggestion: why not add the ability to change/restore the .htaccess file when the command run instead of simply print an help?

**Comment by wdalmut** [comment]
hi @gremo interesting idea. if i have enough time i will work on it. Or if you prefer feel free to open a PR.

bests
Walter

**Comment by armellin** [comment]
IMHO, with an existing .htaccess, it could be difficult to let the program decide where exactly the snippet is supposed to be placed. All in all, it's a one-time operation: the copy&paste strategy seems acceptable.

**Comment by armellin** [comment]
Furthermore, .htaccess might be 'not writable'...

**Comment by nfodev** [comment]
I agree with armellin, there are just too many variables you would have to deal with when modifying a .htaccess
And indeed, you only need to copy+paste it once.
