### ISSUE TITLE
Cannot run program Win32 valide

### ISSUE THREAD

**Issue by xorgxx** [matatirosolutions/CorleyMaintenanceBundle#12]
Hi thank for this helpfull bundle.

i have this error : 

```
> bin/console corley:maintenance:soft-lock on
Cannot run program "D:\Programmation\Web\root_www\menefer\bin\console" (in directory "D:\Programmation\Web\root_www\menefer"): CreateProcess error=193, %1 n’est pas une application Win32 valide
```

my config : windows 10 64x, WampServer Version 3.0.4 64bit, SF 3

Merci

**Comment by wdalmut** [comment]
Probably you have to use `php` on windows

``` sh
php D:\Programmation\Web\root_www\menefer\bin\console" (in directory "D:\Programmation\Web\root_www\menefer
```

it works?

**Comment by xorgxx** [comment]
i find my probleme it was mistek in command line !

```
bin/console corley:maintenance:soft-lock on
```

to 

```
s corley:maintenance:soft-lock on
```

(phpstorm)

Thank for help
but still i deed not get working bundle lock or unlock deed not work for me.

**Comment by wdalmut** [comment]
To lock and unlock you have to change your apache `.htaccess` file. Check the `dump` command
