### ISSUE TITLE
Can't override public folder from web to public_html

### ISSUE THREAD

**Issue by dancostinel** [matatirosolutions/CorleyMaintenanceBundle#13]
Hi.

Trying to set up the bundle. I've installed it in a separate, for testing purposes, project and it worked if I used ```web``` as my public directory.
Once I renamed ```web``` into ```public_html```, and I run:
```$ php bin/console corley:maintenance:soft-lock on```
and I refresh the front page, nothing changes, and the front page is still displayed. (tried to clear the cache too).
I also used the config for using a different public dir, as described in the docs:
```
// app/config/config.yml
corley_maintenance:
    web: public_html
```

Any suggestions?

Thanks!

**Comment by wdalmut** [comment]
I moved the `web` folder

```
mv web public_html
```

then run the php web server:

```
php -S 0:8080 -t public_html public_html/app_dev.php
```

the configuration `config.yml` is:

```php
corley_maintenance:
  web: public_html
```

Then i put the web site in maintenance mode:

```
./bin/console corley:maintenance:soft-lock on
```

And the web site locked correctly.

do you follow another workflow?

**Comment by dancostinel** [comment]
Hi,
I'm using a slightly different one, but I don't think this is the problem (Symfony3.2.4).
1. I updated my apache2 virtual host: from ```web``` to ```public_html```
2. I renamed the Symfony dir from ```web``` to ```public_html```
3. I made the change in ```composer.json``` and dumped it:
```"symfony-web-dir": "public_html",```
```$ composer dump-autoload -o```
4. Installed the bundle: ```composer require corley/maintenance-bundle```
5. AppKernel.php: ```new Corley\MaintenanceBundle\CorleyMaintenanceBundle(),```
6. in ```config.yml```
```
corley_maintenance:
    web: public_html
```
7. ```php bin/console corley:maintenance:soft-lock on```
8. Reloaded the page and still the site front page is present, and not the maintenance-bundle default one.

I'm not making something right?
Thanks.

**Comment by wdalmut** [comment]
Hi,

yes i see the problem. I will work on it!

Thank you!
Walter

**Comment by wdalmut** [comment]
Hi,

i found the problem.

We have to use the maintenance full path

```
corley_maintenance:
  web: "%kernel.root_dir%/../public_html"
``` 

In that way the listener check the right path on disk.
