### ISSUE TITLE
Are there Symfony 4 plans?

### ISSUE THREAD

**Issue by steveWinter** [matatirosolutions/CorleyMaintenanceBundle#14]
The folder structure of Symfony 4 has changed - are there any plans to update this module to support sf 4?

**Comment by steveWinter** [comment]
RTFM and I discover that I can configure the public folder, which is half the issues I was discovering resolved.

The other is that corley:maintenance:dump-apache seems to no-loner be registered?

**Comment by foo123** [comment]
I am interested in symfony 4 version of this bundle as well

**Comment by wdalmut** [comment]
Any one is interested to maintain this bundle? I am not working in PHP anymore.

**Comment by steveWinter** [comment]
Sure thing - I’d be happy to pick this up and create a new version which supports SF4 (would need to be a new major version as the default folders are different, so BC breaks for <=SF3.x)

**Comment by wdalmut** [comment]
good @steveWinter if you want i can transfer this repo to you ok?

**Comment by steveWinter** [comment]
By all means!

**Comment by wdalmut** [comment]
request sent!

**Comment by steveWinter** [comment]
@wdalmut can you also please add 'matatirosolutions' as a maintainer on packagist so that I can update the github URL?

**Comment by wdalmut** [comment]
@steveWinter i have added matatirosolutions as packagist maintainer
