### ISSUE TITLE
Error on lock on

### ISSUE THREAD

**Issue by daodevinc** [matatirosolutions/CorleyMaintenanceBundle#21]
Hi guy,

I have install your package on Symfony 4.2

when i want to lock on, i have this error. I think the directory have an error : i'm always in /web directory : 

![image](https://user-images.githubusercontent.com/9304947/71764533-36363000-2ee9-11ea-96da-299b6316e932.png)

Thanks.

**Comment by steveWinter** [comment]
From what I can tell from that screenshot it looks like you're using this with a Flex project and so you don't have a `web` folder, but a `public` folder instead. Correct?

For BC purposes this bundle defaults to the pre-Flex folder structure -  so you need to add a config file which sets the path to your 'web' folder.

```yaml
# config/packages/corley_maintenance.yml
corley_maintenance:
    web: public
```

See the the [Configuration section](https://github.com/matatirosolutions/CorleyMaintenanceBundle#configuration) of the README.md for details of the options and their default values.

If I've misunderstood the problem and this doesn't solve things, could you email (steve at msdev dot co dot uk) an 'un-redacted' version of the screenshot so I can see a little more of the issue and offer further suggestions.

**Comment by daodevinc** [comment]
> 
> 
> From what I can tell from that screenshot it looks like you're using this with a Flex project and so you don't have a `web` folder, but a `public` folder instead. Correct?
> 
> For BC purposes this bundle defaults to the pre-Flex folder structure - so you need to add a config file which sets the path to your 'web' folder.
> 
> ```yaml
> # config/packages/corley_maintenance.yml
> corley_maintenance:
>     web: public
> ```
> 
> See the the [Configuration section](https://github.com/matatirosolutions/CorleyMaintenanceBundle#configuration) of the README.md for details of the options and their default values.
> 
> If I've misunderstood the problem and this doesn't solve things, could you email (steve at msdev dot co dot uk) an 'un-redacted' version of the screenshot so I can see a little more of the issue and offer further suggestions.

Yes indeed thank you, my DocumentRoot being called "web", it confused me, and it is indeed a public folder that I have. Thanks for the tip!

**Comment by steveWinter** [comment]
Great - glad you got things solved!
