### ISSUE TITLE
 composer.json depending symfony 2.3> =,  ~ 2.4 packagist.org

### ISSUE THREAD

**Issue by radli** [matatirosolutions/CorleyMaintenanceBundle#3]
Hello, I do not understand one thing, why is composer.json depending symfony 2.3>=, packagist.org written ~2.4?
Thanks!

**Comment by wdalmut** [comment]
Packagist use a repository tag that is old and use `~2.4` i tag immediately with a new setting (>=2.3,<3).

**Comment by wdalmut** [comment]
Solved in v0.1.8

**Comment by wdalmut** [comment]
thanks @radli
