### ISSUE TITLE
dependency on a non-existent service "request_stack".

### ISSUE THREAD

**Issue by narendrakothule** [matatirosolutions/CorleyMaintenanceBundle#4]
I am using symfony 2.3.36 
installed this plugin but  started getting error "The service "corley_maintenance.soft_lock" has a dependency on a non-existent service "request_stack".

any solution?

**Comment by wdalmut** [comment]
Sadly the `request_stack` feature is suitable only for `Symfony2 >= 2.4` here is the doc: http://symfony.com/blog/new-in-symfony-2-4-the-request-stack

**Comment by wdalmut** [comment]
I update the `composer.json` using Symfony 2.4 as a requirement

**Comment by wdalmut** [comment]
thanks for this issue. if you fix the lack of support for sf >= 2.3 open a PR.

Thank you so much
Bests
Walter
