### ISSUE TITLE
Compatibility with Symfony 3

### ISSUE THREAD

**Issue by TomaszKotlarek** [matatirosolutions/CorleyMaintenanceBundle#8]
Is there anything in this bundle what might cause the problem when used in Symfony 3?

**Comment by wdalmut** [comment]
Hi, 

Version 0.2.0 should be stable with Symfony3

**Comment by wdalmut** [comment]
With symfony 3 the `dialog` helper is no longer available and with `Symfony3` locking commands are not available. I will update from `dialog` to `question` helper asap.

**Comment by wdalmut** [comment]
Resolved in tag `0.2.1`
